package main.java.views;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.plaf.basic.BasicTableHeaderUI;
import javax.swing.table.JTableHeader;

import main.java.models.Status;
import main.java.views.CustomTableHeaderUI;


public class AdminView extends javax.swing.JFrame {
    private JComboBox<Status> statusTypeComboBox;
    private Date date;
    private SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM,  yyyy");
    
    public AdminView() throws SQLException {
        this.getContentPane().setBackground(new Color(229, 229, 229));
        
        statusTypeComboBox = new JComboBox<Status>(); 
        
        initComponents();

        // table
        JTableHeader head = apptTable.getTableHeader();
        head.setDefaultRenderer(new CustomTableHeaderUI());
        head.setUI(new BasicTableHeaderUI() {
            @Override
            public void installDefaults() { super.installDefaults(); }
        });
        apptTable.setShowGrid(false);
        date = new Date();
        String formattedDate = formatter.format(date);
        dateLabel.setText(formattedDate);
        

        Border roundedBorder = new LineBorder(Color.white, 10, true);
        tableScrollPane.setBorder(roundedBorder);
        JScrollBar sb = tableScrollPane.getVerticalScrollBar();
        sb.setBackground(Color.white);
        sb.setPreferredSize(new Dimension(5, sb.getPreferredSize().height)); 
        sb.setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() { this.thumbColor = Color.GRAY; }
            
            @Override
            protected JButton createDecreaseButton(int orientation) { return createZeroButton(); }

            @Override
            protected JButton createIncreaseButton(int orientation) { return createZeroButton(); }

            private JButton createZeroButton() {
                JButton button = new JButton();
                button.setPreferredSize(new Dimension(0, 0));
                button.setMinimumSize(new Dimension(0, 0));
                button.setMaximumSize(new Dimension(0, 0));
                return button;
            }
        });

        addNewApptBtn.setFocusPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apptPopupMenu = new javax.swing.JPopupMenu();
        delMenuItem = new javax.swing.JMenuItem();
        logoutBtn = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        apptTable = new javax.swing.JTable();
        addNewApptBtn = new javax.swing.JButton();
        filterComboBox = new javax.swing.JComboBox<>();
        sortByLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        userAvatar = new main.java.views.ImageAvatar();
        headerTitleLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        subHeaderLabel = new javax.swing.JLabel();
        apptLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();

        apptPopupMenu.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        apptPopupMenu.setName(""); // NOI18N

        delMenuItem.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        delMenuItem.setText("Delete");
        delMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delMenuItemActionPerformed(evt);
            }
        });
        apptPopupMenu.add(delMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setMinimumSize(new java.awt.Dimension(736, 414));

        logoutBtn.setBackground(new java.awt.Color(255, 89, 123));
        logoutBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);

        tableScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPane.setBorder(null);
        tableScrollPane.setToolTipText("");
        tableScrollPane.setColumnHeaderView(null);
        tableScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableScrollPane.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        tableScrollPane.setHorizontalScrollBar(null);
        tableScrollPane.setVerifyInputWhenFocusTarget(false);
        tableScrollPane.setViewportView(apptTable);

        apptTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        apptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        apptTable.setToolTipText("");
        apptTable.setFillsViewportHeight(true);
        apptTable.setRowHeight(40);
        apptTable.setRowMargin(10);
        apptTable.setSelectionBackground(new java.awt.Color(255, 153, 204));
        apptTable.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(apptTable);

        addNewApptBtn.setBackground(new java.awt.Color(255, 198, 211));
        addNewApptBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        addNewApptBtn.setForeground(new java.awt.Color(255, 89, 123));
        addNewApptBtn.setText("+ ADD NEW");
        addNewApptBtn.setActionCommand("");
        addNewApptBtn.setBorder(null);
        addNewApptBtn.setRolloverEnabled(false);

        filterComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Pending", "Confirmed", "Completed", "Canceled" }));

        sortByLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        sortByLabel.setText("Sort By:");

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new LineBorder(Color.white, 10, true));
        headerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        userAvatar.setBackground(new java.awt.Color(132, 132, 132));
        userAvatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/main/resources/person-svgrepo-com.png"))); // NOI18N

        headerTitleLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 21)); // NOI18N
        headerTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        headerTitleLabel.setText("Admin Dashboard");
        headerTitleLabel.setToolTipText("");

        userLabel.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        userLabel.setForeground(new java.awt.Color(102, 102, 102));
        userLabel.setText("Administrator");

        subHeaderLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        subHeaderLabel.setForeground(new java.awt.Color(102, 102, 102));
        subHeaderLabel.setText("Final Destination Clinic");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel)
                    .addComponent(headerTitleLabel)
                    .addComponent(subHeaderLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(headerTitleLabel)
                        .addGap(3, 3, 3)
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subHeaderLabel))
                    .addComponent(userAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        apptLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        apptLabel.setForeground(new java.awt.Color(51, 51, 51));
        apptLabel.setText("All Appointments");

        dateLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(153, 153, 153));
        dateLabel.setText("11 May 2024");

        delBtn.setBackground(new java.awt.Color(255, 84, 84));
        delBtn.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 255));
        delBtn.setText("DELETE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1267, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apptLabel)
                                    .addComponent(dateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sortByLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addNewApptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addNewApptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sortByLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(apptLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel))
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* GETTER METHODS OF THE COMPONENTS */
    
    public JButton getDelBtn() { return delBtn; }

    public JTable getApptTable() { return apptTable; }
 
    public JComboBox<Status> getStatusTypeComboBox() { return statusTypeComboBox; }

    public javax.swing.JPopupMenu getApptPopupMenu() { return apptPopupMenu; }

    public javax.swing.JComboBox<String> getFilterComboBox() { return filterComboBox; }

    public javax.swing.JButton getLogoutBtn() { return logoutBtn; }

    public javax.swing.JButton getAddNewApptBtn() { return addNewApptBtn; }
    
    
    /* USER MESSAGE METHODS */
    
    public void showMessageBox(String msg, String title, int icon) {
         JOptionPane.showMessageDialog(this, msg, title, icon);
    }

    
    public boolean showConfirmBox(String msg, String title) {
        boolean isConfirmed = false;
        
        int res = JOptionPane.showConfirmDialog(this, msg, title, JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        if(res == JOptionPane.YES_OPTION) isConfirmed = true;
      
        return isConfirmed;
    }
    
   public String showStatusPatientBox() {
        String[] opts = {"New", "Existing"};        
        int index = JOptionPane.showOptionDialog(null, "Is the patient new or old?", "Patient Record", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opts, null);
        return opts[index];
    }
    
    private void delMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delMenuItemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_delMenuItemActionPerformed
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewApptBtn;
    private javax.swing.JLabel apptLabel;
    private javax.swing.JPopupMenu apptPopupMenu;
    private javax.swing.JTable apptTable;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delBtn;
    private javax.swing.JMenuItem delMenuItem;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerTitleLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JLabel subHeaderLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private main.java.views.ImageAvatar userAvatar;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

}
