/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.views;

import java.awt.Color;
import main.java.models.Appointment;
import main.java.utils.Utils;

/**
 *
 * @author Jazz Cruz
 */
public class ApptWindowView extends javax.swing.JFrame {
    private Appointment appt;
    /**
     * Creates new form ApptWindowView
     */
    public ApptWindowView(Appointment appt) {
        this.appt = appt;

        initComponents();
        
        patientName.setText(appt.getPatient().getName());
        patientAge.setText(String.valueOf(appt.getPatient().getAge()));
        patientSex.setText(appt.getPatient().getSex());
        docName.setText(appt.getDoctor().toString());
        visitType.setText(appt.getVisitTypeName());
        status.setText(appt.getStatus());
        date.setText(Utils.formatDate(appt.getDate()));
        time.setText(Utils.convertTimeFormat(appt.getStartTime()) + " - " + Utils.convertTimeFormat(appt.getEndTime()));
        
        getContentPane().setBackground(Color.white);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDetLabel = new javax.swing.JLabel();
        patNameLabel = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        patientSexLabel = new javax.swing.JLabel();
        patAgeLabel = new javax.swing.JLabel();
        patientAge = new javax.swing.JLabel();
        patientSex = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visitType = new javax.swing.JLabel();
        visitTypeLabel = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        docName = new javax.swing.JLabel();
        ApptDetLabel = new javax.swing.JLabel();
        docnameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Final Destination Clinic");

        patientDetLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        patientDetLabel.setText("PATIENT DETAILS");

        patNameLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        patNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        patNameLabel.setText("NAME");

        patientName.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        patientName.setText("Gabbi Garcia");

        patientSexLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        patientSexLabel.setForeground(new java.awt.Color(153, 153, 153));
        patientSexLabel.setText("SEX");

        patAgeLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        patAgeLabel.setForeground(new java.awt.Color(153, 153, 153));
        patAgeLabel.setText("AGE");

        patientAge.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        patientAge.setText("26");

        patientSex.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        patientSex.setText("Female");

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 22)); // NOI18N
        jLabel1.setText("Appointment Details");

        visitType.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        visitType.setText("Check-up");

        visitTypeLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        visitTypeLabel.setForeground(new java.awt.Color(153, 153, 153));
        visitTypeLabel.setText("VISIT TYPE");

        date.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        date.setText("20 May 2024");

        timeLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(153, 153, 153));
        timeLabel.setText("TIME");

        time.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        time.setText("2:00 PM - 5:00 PM");

        docName.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        docName.setText("Dr. James Reid");

        ApptDetLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        ApptDetLabel.setText("APPOINTMENT DETAILS");

        docnameLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        docnameLabel.setForeground(new java.awt.Color(153, 153, 153));
        docnameLabel.setText("DOCTOR");

        dateLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(153, 153, 153));
        dateLabel.setText("DATE");

        status.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        status.setText("Pending");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Below are the full details of the appointment.");

        statLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        statLabel.setForeground(new java.awt.Color(153, 153, 153));
        statLabel.setText("STATUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitType)
                            .addComponent(docName)
                            .addComponent(docnameLabel)
                            .addComponent(ApptDetLabel)
                            .addComponent(dateLabel)
                            .addComponent(date))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time)
                            .addComponent(timeLabel)
                            .addComponent(status)
                            .addComponent(statLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientAge)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(visitTypeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientName)
                                    .addComponent(patNameLabel)
                                    .addComponent(patientDetLabel)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(patAgeLabel)
                                        .addGap(94, 94, 94)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patientSex)
                                            .addComponent(patientSexLabel))))))
                        .addGap(194, 194, 194))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(patientDetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientName)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patAgeLabel)
                            .addComponent(patientSexLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientSex)
                        .addGap(3, 3, 3))
                    .addComponent(patientAge))
                .addGap(32, 32, 32)
                .addComponent(ApptDetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(docnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(docName)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitTypeLabel)
                    .addComponent(statLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitType)
                    .addComponent(status))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(time))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApptWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApptWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApptWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApptWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ApptWindowView().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApptDetLabel;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel docName;
    private javax.swing.JLabel docnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patAgeLabel;
    private javax.swing.JLabel patNameLabel;
    private javax.swing.JLabel patientAge;
    private javax.swing.JLabel patientDetLabel;
    private javax.swing.JLabel patientName;
    private javax.swing.JLabel patientSex;
    private javax.swing.JLabel patientSexLabel;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel status;
    private javax.swing.JLabel time;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel visitType;
    private javax.swing.JLabel visitTypeLabel;
    // End of variables declaration//GEN-END:variables
}
